# Generated by Django 5.2.17 on 2026-10-07 05:11

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_alter_card_expiry_month_alter_card_expiry_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=Decimal('100000.00'), max_digits=12),
        ),
    ]
