# Generated by Django 5.2.17 on 2026-10-08 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_card_credit_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='blocked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
