services:
  db:
    image: mysql:8.4
    container_name: payment_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

  mailpit:
    image: axllent/mailpit:latest
    container_name: payment_mailpit
    restart: unless-stopped
    ports:
      - "8025:8025"   # web inbox: http://localhost:8025
      - "1025:1025"   # SMTP

  django:
    build: ./django_service
    container_name: payment_django
    env_file: .env
    environment:
      DB_HOST: db
      DB_PORT: "3306"
      EMAIL_HOST: mailpit
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      mailpit:
        condition: service_started

  fastapi:
    build: ./fastapi_service
    container_name: payment_fastapi
    env_file: .env
    environment:
      DB_HOST: db
      DB_PORT: "3306"
      EMAIL_HOST: mailpit
    ports:
      - "8001:8001"
    depends_on:
      db:
        condition: service_healthy
      mailpit:
        condition: service_started

  frontend:
    build: ./frontend
    container_name: payment_frontend
    ports:
      - "5173:80"
    depends_on:
      - django
      - fastapi

volumes:
  mysql_data: